### ISSUE TITLE
Firefox Bug .animateLayer()

### ISSUE THREAD

**Issue by tobiasharth** [caleb531/jcanvas#236] opened 2016-04-07 09:05 UTC
Hey,

i try to animate a layer with .animateLayer(). But in Firefox i recived a error. 

Code:
```javascript
$('#canvas').animateLayer('layer1', {
	strokeWidth: 1.1,
	strokeStyle: 'rgb(89,91,94)',
	shadowBlur: 0
}, 300);
```

Firefox Error:
```javascript
TypeError: e is null
A()
B()
H.propHooks._default.set()
H.prototype.run()
N/i()
fa.fx.tick()
```

This error count up and up and up and up ...
Perhaps it is related to commit f31504e

Thanks,
Tobi

**Comment by caleb531** [comment] 2016-04-08 18:50
Strange... I have two questions:

1. What jCanvas version are you using?
2. Can you test your code using the unminified jCanvas source so the error message is more descriptive?

**Comment by tobiasharth** [comment] 2016-04-18 14:46
I use the version `16.04.01`.

This is the error message with the unminified jCanvas source:

```javascript
TypeError: rgb is null
_colorToRgbArray()
_animateColor()
H.propHooks._default.set()
H.prototype.run()
N/i()
fa.fx.tick()
```

**Comment by caleb531** [comment] 2016-04-24 03:11
My sincere apologies for the delay in response.

I just ran this code on Firefox 45 on OS X with no issues whatsoever; the circle renders without errors.

```js
$('canvas')
.drawArc({
  layer: true,
  strokeWidth: 0,
  fillStyle: '#6c3',
  x: 100, y: 100,
  radius: 50
})
.animateLayer('layer1', {
  strokeWidth: 1.1,
  strokeStyle: 'rgb(89,91,94)',
  shadowBlur: 0
}, 300);
```

What version of Firefox are you using and on what platform?

Thanks,
Caleb

**Comment by tobiasharth** [comment] 2016-04-30 09:29
I use the same firefox version on the same OS. 

Maybe good to know: i have 22 layers, they will update and animate on a click.

**Comment by caleb531** [comment] 2016-05-02 16:11
This is still very strange. After modifying my above code snippet to fit your description (animating lines on click), I am still unable to reproduce the issue in the [jCanvas Sandbox](http://projects.calebevans.me/jcanvas/sandbox/):

```
$('canvas').drawLine({
  layer: true,
  name: 'layer1',
  strokeStyle: '#000',
  strokeWidth: 10,
  x1: 100, y1: 50,
  x2: 100, y2: 150,
  x3: 200, y3: 100,
  x4: 150, y4: 200,
  click: function(layer) {
    $('canvas').animateLayer(layer, {
		strokeWidth: 1.1,
        strokeStyle: 'rgb(255,0,0)',
        shadowBlur: 0
    }, 1000);
  }
});
```

**Comment by caleb531** [comment] 2016-06-05 23:45
Since we are at an impasse, I'm closing this issue for now. If you can successfully reproduce the issue in the jCanvas Sandbox, I will gladly reopen. :)

Caleb

**Comment by tobiasharth** [comment] 2016-06-06 14:13
Hey! Sorry for the delay in response.

With following code i can successfully reproduce the issue in the jCanvas Sandbox:

```javascript
var thetype = false;
var thecanvas = {
	'from-1-to-2': {
		x1: 298.5, y1: 104.5,
		x2: 639.5, y2: 104.5
	},
	'from-2-to-3': {
		x1: 660.5, y1: 127.5,
		x2: 660.5, y2: 231.5
	},
	'from-2-to-16': {
		x1: 683.5, y1: 104.5,
		x2: 1161.5, y2: 104.5,
		x3: 1161.5, y3: 751.5
	},
	'from-3-to-4': {
		x1: 637.5, y1: 255.5,
		x2: 275.5, y2: 255.5,
		x3: 275.5, y3: 371.5
	},
	'from-3-to-5': {
		x1: 647.5, y1: 245.5,
		x2: 82.5, y2: 245.5,
		x3: 82.5, y3: 371.5
	},
	'from-3-to-12': {
		x1: 674.5, y1: 245.5,
		x2: 1240.5, y2: 245.5,
		x3: 1240.5, y3: 373.5
	},
	'from-3-to-9': {
		x1: 680.5, y1: 255.5,
		x2: 1047.5, y2: 255.5,
		x3: 1047.5, y3: 373.5
	},
	'from-4-to-6': {
		x1: 275.5, y1: 418.5,
		x2: 275.5, y2: 503.5
	},
	'from-4-to-14': {
		x1: 298.5, y1: 394.5,
		x2: 660.5, y2: 394.5,
		x3: 660.5, y3: 751.5
	},
	'from-5-to-7': {
		x1: 82.5, y1: 418.5,
		x2: 82.5, y2: 645.5,
		x3: 251.5, y3: 645.5
	},
	'from-5-to-8': {
		x1: 91.5, y1: 410.5,
		x2: 91.5, y2: 850.5,
		x3: 275.5, y3: 850.5,
		x4: 275.5, y4: 798.5
	},
	'from-5-to-13': {
		x1: 74.5, y1: 410.5,
		x2: 74.5, y2: 470.5,
		x3: 381.5, y3: 470.5,
		x4: 381.5, y4: 774.5,
		x5: 445.5, y5: 774.5,
	},
	'from-6-to-7': {
		x1: 275.5, y1: 548.5,
		x2: 275.5, y2: 622.5
	},
	'from-6-to-8': {
		x1: 253.5, y1: 525.5,
		x2: 175.5, y2: 525.5,
		x3: 175.5, y3: 774.5,
		x4: 253.5, y4: 774.5
	},
	'from-6-to-13': {
		x1: 299.5, y1: 525.5,
		x2: 461.5, y2: 525.5,
		x3: 461.5, y3: 757.5,
	},
	'from-7-to-8': {
		x1: 275.5, y1: 667.5,
		x2: 275.5, y2: 752.5
	},
	'from-9-to-10': {
		x1: 1047.5, y1: 418.5,
		x2: 1047.5, y2: 501.5
	},
	'from-9-to-15': {
		x1: 1024.5, y1: 394.5,
		x2: 854.5, y2: 394.5,
		x3: 854.5, y3: 751.5
	},
	'from-9-to-14': {
		x1: 1034.5, y1: 384.5,
		x2: 652.5, y2: 384.5,
		x3: 652.5, y3: 759.5
	},
	'from-9-to-13': {
		x1: 1034.5, y1: 404.5,
		x2: 468.5, y2: 404.5,
		x3: 468.5, y3: 751.5
	},
	'from-10-to-11': {
		x1: 1047.5, y1: 547.5,
		x2: 1047.5, y2: 622.5
	},
	'from-11-to-12': {
		x1: 1240.5, y1: 417.5,
		x2: 1240.5, y2: 644.5,
		x3: 1070.5, y3: 644.5
	}
}

$.each( thecanvas , function(key, value) {
	var config = {
		layer: true,
		name: key,
		strokeStyle: 'rgba(0,0,0,1)',
		strokeWidth: 1.1
	}
	$.extend(config, value);
	$('canvas').drawLine(config);
});

$('canvas').click(function(){
	$.each(thecanvas, function(key, value) {
		if (thetype == false) {
			$('canvas').animateLayer(key, {
				strokeWidth: 2,
				shadowColor: 'rgb(230,25,25)',
				strokeStyle: 'rgb(230,25,25)',
				shadowBlur: 20
			}, 300);
		} else {
			$('canvas').animateLayer(key, {
				strokeWidth: 1.1,
				shadowColor: 'rgb(0,0,0)',
				strokeStyle: 'rgb(0,0,0)',
				shadowBlur: 0
			}, 300);
		}
	});
	thetype = (thetype) ? false : true;
});
```

**Comment by caleb531** [comment] 2016-06-06 19:57
Excellent, thanks for for Sandbox code.

And great news! I was able to reproduce the bug with your code, and I was successful in finding the cause of the bug and fixing it. Please check [branch develop](https://github.com/caleb531/jcanvas/blob/develop/jcanvas.js) for the latest build and let me know if this works for you so I can merge it in. :)

**Comment by tobiasharth** [comment] 2016-06-08 13:49
Hey! It works perfectly! Thanks :)

**Closed** 2016-06-08 16:02 UTC
